# Generated by Django 3.0.6 on 2020-05-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKE_USERS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationtoken',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
