# Generated by Django 3.0.6 on 2020-05-13 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=1024)),
                ('result', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('ord_id', models.IntegerField()),
                ('body_md', models.CharField(max_length=24576)),
                ('father_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SKE_COURSES.Course')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SKE_COURSES.CourseUpload')),
            ],
        ),
    ]
