# Generated by Django 3.0.6 on 2020-05-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKE_COURSES', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='body_md',
            field=models.TextField(max_length=24576),
        ),
    ]
