# Generated by Django 3.0.6 on 2020-05-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKE_COURSES', '0002_auto_20200513_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='body_html',
            field=models.TextField(blank=True, max_length=49152),
        ),
    ]
