# Generated by Django 3.0.6 on 2020-05-13 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SKE_COURSES', '0003_course_body_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('ord_id', models.IntegerField()),
                ('path', models.CharField(max_length=1024)),
                ('start_code', models.TextField(max_length=24576)),
                ('body_md', models.TextField(max_length=24576)),
                ('body_html', models.TextField(blank=True, max_length=49152)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SKE_COURSES.Course')),
            ],
        ),
    ]
