# Generated by Django 3.0.6 on 2020-05-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKE_CONTESTS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
