# Generated by Django 3.0.6 on 2020-05-14 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SKE_CONTESTS', '0002_contest_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContestProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SKE_CONTESTS.Contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContestTaskPackageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(allow_folders=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('result', models.IntegerField(choices=[(0, 'NIE SPRAWDZONA'), (1, 'BŁĄD PODCZAS SPRAWDZANIA'), (2, 'POPRAWNIE WGRANA')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_id', models.IntegerField()),
                ('timelimit', models.IntegerField()),
                ('submlimit', models.IntegerField()),
                ('body', models.TextField()),
                ('title', models.CharField(max_length=256)),
                ('path', models.FilePathField(allow_folders=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SKE_CONTESTS.Contest')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SKE_CONTESTS.ContestTaskPackageUpload')),
            ],
        ),
    ]
