# Generated by Django 3.0.6 on 2020-05-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKE_CONTESTS', '0003_contesttask_contesttaskpackageupload_usercontestprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contesttask',
            name='path',
            field=models.CharField(max_length=1024),
        ),
    ]
