# Generated by Django 3.0.6 on 2020-05-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKE_CONTESTS', '0004_auto_20200514_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contesttaskpackageupload',
            name='path',
            field=models.CharField(max_length=1024),
        ),
    ]
