# Generated by Django 3.0.6 on 2020-05-14 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SKE_CONTESTS', '0005_auto_20200514_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contesttask',
            old_name='submlimit',
            new_name='sublimit',
        ),
    ]
