# Generated by Django 3.0.6 on 2020-05-14 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SKE_CONTESTS', '0006_auto_20200515_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestTaskTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024)),
                ('ord_id', models.IntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SKE_CONTESTS.ContestTask')),
            ],
        ),
    ]
