# Generated by Django 3.0.6 on 2020-05-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKE_CONTESTS', '0008_contesttasksubmission_contesttasksubmissiontest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contesttasksubmission',
            name='code',
            field=models.TextField(default='#Hello', max_length=24576),
            preserve_default=False,
        ),
    ]
