# Generated by Django 3.0.6 on 2020-05-15 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SKE_CONTESTS', '0010_auto_20200515_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contesttasksubmissiontest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_tests', to='SKE_CONTESTS.ContestTaskTest'),
        ),
    ]
