# Generated by Django 3.0.6 on 2020-05-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKE_CONTESTS', '0012_auto_20200515_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='contesttasksubmission',
            name='score',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='contesttasksubmissiontest',
            name='score',
            field=models.IntegerField(default=-1),
        ),
    ]
