# Generated by Django 3.0.6 on 2020-05-16 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SKE_CONTESTS', '0013_auto_20200515_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contesttasksubmissiontest',
            options={'ordering': ['test__ord_id']},
        ),
    ]
